apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-products-infra
  labels:
    app: app-products-infra
spec:

  selector:
    matchLabels:
      app: app-products-infra
  replicas: 2
  strategy:
    type: RollingUpdate


  template:
    metadata:
      labels:
        app: app-products-infra
    spec:
      containers:
      - name: app-products-infra
        image: kpradeep/app-products-infra
        imagePullPolicy: IfNotPresent
        
        ports:
        - containerPort: 8888
