
apiVersion: v1
kind: Service
metadata:
  name: app-products-infra-service
spec:
  selector:
    app: app-products-infra
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888

